### ISSUE TITLE
pug-2.0.0.min.js is not included

### ISSUE THREAD

**Issue by DougBeney** [yivo/pug-ruby#2]
Hello, great gem!

Running into a problem though. pug-2.0.0.min.js is not included when I install your gem.

So this: `Pug.use "2.0.0"` does not work.

I am currently using this instead for the moment: `Pug.use "2.0.0-beta10" `

Here are the different pug js files that are included.

```
pug-2.0.0-beta10.min.js
pug-2.0.0-beta11.min.js
pug-2.0.0-beta12.min.js
pug-2.0.0-beta1.min.js
pug-2.0.0-beta2.min.js
pug-2.0.0-beta3.min.js
pug-2.0.0-beta4.min.js
pug-2.0.0-beta5.min.js
pug-2.0.0-beta6.min.js
pug-2.0.0-beta7.min.js
pug-2.0.0-beta8.min.js
pug-2.0.0-beta9.min.js
pug-2.0.0-rc.1.min.js
pug-2.0.0-rc.2.min.js
pug-2.0.0-rc.3.min.js
pug-2.0.0-rc.4.min.js
```

**Comment by yivo** [comment]
Hi @DougBeney 

Thank you for your feedback.

pug 2.0.0 is not released yet :)

You can check this on the official pug github repo: https://github.com/pugjs/pug/releases

Also you can check manually by running `npm show pug versions`.

This produces the next output:
<img width="240" alt="screen shot 2017-11-15 at 7 10 58 pm" src="https://user-images.githubusercontent.com/7421323/32849805-ee146fc4-ca38-11e7-8592-a953f1936310.png">

So the latest pug version is pug-2.0.0-rc.4. `rc` means release candidate. When pug 2.0.0 will be out (or any other updates) I will update the gem.

**Comment by DougBeney** [comment]
Ah, my bad. Thanks for the quick reply and I'm glad to see you're adding more features to this plugin.

Currently updating [Jekyll-Pug](http://jekyll-pug.dougie.io/) to allow for selecting built-in Pug runtimes. :)

**Comment by DougBeney** [comment]
By the way, I was on pug-ruby version 1 previously, where pug-cli was required. 

By using the system compiler on pug-ruby, with the latest 2.x version, it said that I needed the regular pug package installed globally. 

So, is pug-cli no longer a required NPM package? (Just pug)

**Comment by DougBeney** [comment]
Also, on pug-2.0.0-beta10, includes are working perfectly, even though the documentation said they would not.

**Comment by yivo** [comment]
@DougBeney If you want to use system pug you need to `npm i -g pug` (not pug-cli, just pug). It [figures out](https://github.com/yivo/pug-ruby/blob/master/lib/jade-pug/system-compiler.rb#L90) where your global NPM packages are installed, then [requires](https://github.com/yivo/pug-ruby/blob/master/lib/jade-pug/system-compiler.rb#L82) engine and [invokes](https://github.com/yivo/pug-ruby/blob/master/lib/jade-pug/compiler.rb#L119) compiler. You don't need CLI utility. It is not used anymore because it has complex API and it is buggy.

**Comment by yivo** [comment]
@DougBeney I believe you are riding system compiler, not shipped. That's why it works. ExecJS doesn't provide any access to native node modules: [link](https://github.com/sstephenson/execjs#faq).

**Comment by yivo** [comment]
@DougBeney I plan to add rich logging so it will be much easier to understand which compiler is being used, especially in projects where you use several versions.

**Comment by DougBeney** [comment]
Very cool. Greatly appreciate it. Glad you added the shipped libraries because now it will be possible for my users to deploy their websites to Siteleaf.

**Comment by yivo** [comment]
@DougBeney Good luck!

About ExecJS and shipped compilers...

It is a bit more complicated. If you use ExecJS with external runtime (just simple system Node.js runtime installation) you will have access to require('fs') and Jade / Pug will fully work. But if you use some embedded V8 runtime like therubyracer require('fs') will fail. If you need only default features of Jade / Pug (no filesystem interaction) I recommend to install gem mini_racer and use shipped compilers since it is fast and doesn't require system Node.js dependency. Don't use therubyracer. It targets Node.js 0.12 which is very old today.

So in your case includes and extends work because you use system Node.js runtime with shipped compilers.
